//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestManagementAPI.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestMgmtEntities : DbContext
    {
        public RestMgmtEntities()
            : base("name=RestMgmtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupMaster> GroupMasters { get; set; }
        public virtual DbSet<TableMaster> TableMasters { get; set; }
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
    }
}
