//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestManagementAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableMaster
    {
        public int Id { get; set; }
        public string TableNo { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    }
}
